name: Terraform Azure (minimal with backend)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform-azure-min.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: true

  # Azure auth (from Secrets)
  ARM_CLIENT_ID:       ${{ secrets.AZURE_AD_APPLICATION_ID }}
  ARM_CLIENT_SECRET:   ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_TENANT_ID:       ${{ secrets.AZURE_AD_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Backend settings (put these as repo variables or secrets)
  TFSTATE_RESOURCE_GROUP:  ${{ vars.TFSTATE_RESOURCE_GROUP }}
  TFSTATE_STORAGE_ACCOUNT: ${{ vars.TFSTATE_STORAGE_ACCOUNT }}
  TFSTATE_CONTAINER:       ${{ vars.TFSTATE_CONTAINER }}
  TFSTATE_KEY:             ${{ vars.TFSTATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Azure Login (service principal)
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ env.ARM_CLIENT_ID }}
          client-secret: ${{ env.ARM_CLIENT_SECRET }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init (AzureRM backend via AAD)
        run: |
          terraform init \
            -backend-config="resource_group_name=${TFSTATE_RESOURCE_GROUP}" \
            -backend-config="storage_account_name=${TFSTATE_STORAGE_ACCOUNT}" \
            -backend-config="container_name=${TFSTATE_CONTAINER}" \
            -backend-config="key=${TFSTATE_KEY}" \
            -backend-config="use_azuread_auth=true"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply (auto-approve)
        run: terraform apply -auto-approve -input=false

