name: Terraform Azure — Manual Plan & Apply

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      ARM_CLIENT_ID:       ${{ secrets.AZURE_AD_APPLICATION_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TFSTATE_RESOURCE_GROUP:  ${{ vars.TFSTATE_RESOURCE_GROUP }}
      TFSTATE_STORAGE_ACCOUNT: ${{ vars.TFSTATE_STORAGE_ACCOUNT }}
      TFSTATE_CONTAINER:       ${{ vars.TFSTATE_CONTAINER }}
      TFSTATE_KEY:             ${{ vars.TFSTATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Azure Login (service principal secret)
        uses: azure/login@v2
        with:
          creds: >-
            {"clientId":"${{ secrets.AZURE_AD_APPLICATION_ID }}",
             "clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}",
             "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
             "tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}"}

      - name: Terraform Init (AzureRM backend via AAD)
        run: |
          terraform init \
            -backend-config="resource_group_name=${TFSTATE_RESOURCE_GROUP}" \
            -backend-config="storage_account_name=${TFSTATE_STORAGE_ACCOUNT}" \
            -backend-config="container_name=${TFSTATE_CONTAINER}" \
            -backend-config="key=${TFSTATE_KEY}" \
            -backend-config="use_azuread_auth=true"

      - name: Validate
        run: |
          terraform fmt -check -recursive || true
          terraform validate

      - name: Plan
        run: terraform plan -input=false -out=tfplan.binary

      - name: Save plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.binary
          retention-days: 7

      - name: Show plan
        run: terraform show -no-color tfplan.binary >> "$GITHUB_STEP_SUMMARY"

  apply:
    name: Terraform Apply (requires approval)
    needs: [ plan ]
    runs-on: ubuntu-latest
    environment: prod
    env:
      TF_IN_AUTOMATION: true
      ARM_CLIENT_ID:       ${{ secrets.AZURE_AD_APPLICATION_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TFSTATE_RESOURCE_GROUP:  ${{ vars.TFSTATE_RESOURCE_GROUP }}
      TFSTATE_STORAGE_ACCOUNT: ${{ vars.TFSTATE_STORAGE_ACCOUNT }}
      TFSTATE_CONTAINER:       ${{ vars.TFSTATE_CONTAINER }}
      TFSTATE_KEY:             ${{ vars.TFSTATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Azure Login (service principal secret)
        uses: azure/login@v2
        with:
          creds: >-
            {"clientId":"${{ secrets.AZURE_AD_APPLICATION_ID }}",
             "clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}",
             "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
             "tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}"}

      - name: Terraform Init (AzureRM backend via AAD)
        run: |
          terraform init \
            -backend-config="resource_group_name=${TFSTATE_RESOURCE_GROUP}" \
            -backend-config="storage_account_name=${TFSTATE_STORAGE_ACCOUNT}" \
            -backend-config="container_name=${TFSTATE_CONTAINER}" \
            -backend-config="key=${TFSTATE_KEY}" \
            -backend-config="use_azuread_auth=true"

      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Apply approved plan
        run: terraform apply -input=false -auto-approve tfplan.binary
